---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    # image: geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest
    image: ubuntu:24.04
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    ansible_remote_tmp: /tmp
provisioner:
  name: ansible
  options:
    v: true
verifier:
  name: ansible
