---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    # image: geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest
    image: geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
